// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"TC001_Custom_Plugin","status":true,"description":"Custom Plugins for TheCrafters001 RPG Maker MV Games.","parameters":{"Game_Title":"Keep Control","Game_Author":"TheCrafters001"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"MOG_TitlePictureCom","status":true,"description":"(v1.6 *) Adiciona comandos em imagens no lugar da janela.","parameters":{"-> Main <<<<<<<<<<<<<<<<<<<<<<<":"","Animation Mode":"2","Left & Right Input":"true","Com Fade-In Duration":"13","Slide X-Axis":"-100","Slide Y-Axis":"0","":"","-> Smart Background  <<<<<<<<<<<<<<<<<<<<<<<":"","Smart Background":"false","Background X-Axis":"0","Background Y-Axis":"0","Background Fade-In Duration":"90","-> Title Sprite <<<<<<<<<<<<<<<<<<<<<<<":"","Title Sprite":"true","Title Sprite X-Axis":"300","Title Sprite Y-Axis":"150","Fade-In Duration":"40","Zoom Effect":"true","Zoom Speed":"40","-> Cursor <<<<<<<<<<<<<<<<<<<<<<<":"","Cursor X-Axis":"0","Cursor Y-Axis":"5","Cursor Visible":"true","Cursor Wave Animation":"true","Cursor Rotation Animation":"false","Cursor Rotation Speed":"0.05","-> Commands <<<<<<<<<<<<<<<<<<<<<<<":"","Command Pos 1":"650,460","Command Pos 2":"660,490","Command Pos 3":"665,520","Command Pos 4":"670,550","Command Pos 5":"345,498","Command Pos 6":"345,530","Command Pos 7":"0,192","Command Pos 8":"0,224","Command Pos 9":"0,256","Command Pos 10":"0,288"}},
{"name":"MOG_TitleSplashScreen","status":true,"description":"(v1.1 *) Adiciona logos antes da tela de título.","parameters":{"Number of Logos":"2","Slash Duration":"60","Splash Fade Duration":"2","Full Screen Mode":"false"}}
];
