// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"TC001_Custom_Plugin","status":true,"description":"Custom Plugins for TheCrafters001 RPG Maker MV Games.","parameters":{"Game_Title":"Keep Control","Game_Author":"TheCrafters001"}},
{"name":"--------------------","status":true,"description":"------------------------------------------------------------","parameters":{}},
{"name":"MOG_TitleSplashScreen","status":true,"description":"(v1.1 *) Adiciona logos antes da tela de título.","parameters":{"Number of Logos":"2","Slash Duration":"60","Splash Fade Duration":"2","Full Screen Mode":"false"}}
];
